### DISCUSSION TITLE
Mathesar on a Synology NAS

### DISCUSSION THREAD

**Discussion by clementquentin** [mathesar-foundation/mathesar#4281] [User Q&A] [answered]
Hi,

I have a Synology NAS, and I updated Container Manager to the beta version in order to run Docker v24 and Docker Compose v2.20.
Yet I can't seem to get Mathesar to work.

I used the standard compose available at : https://raw.githubusercontent.com/mathesar-foundation/mathesar/0.2.0/docker-compose.yml

From what I see, mathesar_service crashes due tu being unable to connect to mathesar_db

mathesar_service shows : 
`django.db.utils.OperationalError: connection failed: connection to server at "XXX.XX.X.X", port 5432 failed: server closed the connection unexpectedly`
and yet mathesar_db shows : 
`LOG:  database system is ready to accept connections`

(I masked the IP even though I don't think it's public.)

Is there anyone here who encountered the same problem ?

I tried to look for a guide designed for Container Manager but didn't find one.

Thanks

**Comment by zackkrida** [comment]
Hi @clementquentin, I've personally installed Mathesar on a Synology NAS, however I use Portainer to manage my containerized applications rather than Container Manager. This [independent website](https://mariushosting.com/how-to-install-portainer-on-your-synology-nas/) is a really awesome resource for managing a Synology NAS, by the way!

This seems less like a synology specific issue and more like a general networking issue. Are there any additional configuration screenshots you could share?

**Reply by clementquentin** [reply]
Hi @zackkrida ! 
I will try installing Mathesar using Portainer and report back here when I'm done.
If I still can't manage to make it work, I'll update logs.
Thanks !

**Reply by clementquentin** [reply]
Hi @zackkrida !

Portainer didn't work better so I went back to Container Manager...

I tried again to install Mathesar by setting up a project.

Here's the window : 
<img width="717" alt="MATHESAR - Container Manager" src="https://github.com/user-attachments/assets/116cb191-b70c-4a8c-af08-e0382b4c230b" />

And here's a file with the compose file and the logs of both mathesar-service and mathesar-db : 
[anonymized-logs.md](https://github.com/user-attachments/files/18950150/anonymized-logs.md)

I can also send you the full logs privately if you want.

**Reply by zackkrida** [reply]
Hi @clementquentin! If you want to join our [Matrix chat](https://wiki.mathesar.org/community/matrix/#chat-rooms) that would be a good place where we can send direct messages and get into more specific details, including your full logs, if needed.

From my initial impressions it can be difficult to tell exactly what the issue might be with the redactions in your docker compose file, but I can still give you something to check:

The value of the x-config variable `POSTGRES_HOST` needs to match the `container_name` value for the `db` service, which our default docker compose file sets as `mathesar_db`. Your redacted config shows the value of `POSTGRES_HOST` as `db_host`. Put another, simpler way, the value of `POSTGRES_HOST` needs to match the Postgres service's `container_name`.

**Reply by clementquentin** [reply]
Here's my compose file 

```yml
x-config: &config
  SECRET_KEY: ${SECRET_KEY:-mykeyz}
  DOMAIN_NAME: ${DOMAIN_NAME:-http://localhost}
  POSTGRES_DB: ${POSTGRES_DB:-mathesar_django}
  POSTGRES_USER: ${POSTGRES_USER:-mathesar}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mathesar}
  POSTGRES_HOST: ${POSTGRES_HOST:-mathesar_db}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:
  service:
    container_name: mathesar_service
    image: mathesar/mathesar:latest
    environment: 
      <<: *config
      DJANGO_SETTINGS_MODULE: config.settings.production
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      MATHESAR_DATABASES: ${MATHESAR_DATABASES:-}
    volumes:
      - ./msar/static:/code/static
      - ./msar/media:/code/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
    expose:
      - "8000"
    ports:
      - ${HOST_PORT:-8000}:8000

  db:
    image: postgres:13
    container_name: mathesar_db
    environment: *config
    expose:
      - "5432"
    volumes:
      - ./msar/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s
```
