### ISSUE TITLE
Add focus indications to focusable elements in components with high usage

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#2837]
## Description
* The Mathesar UI tries to use appropriate DOM elements to enable keyboard accessibility.
* However, we do not have a visible focus state styling on these elements, making it hard/impossible to use Mathesar using keyboard navigation.
* Adding focus indications to all focusable elements will widely improve this.
* * Since it's a huge undertaking to do this in a single PR or track this in a single issue, this issue focuses only on components with high usage, and components visible in initial pages.

## Components to focus
* Button
* AppHeader, Breadcrumb (Components within Breadcrumb)
* SchemaRow
* TableCard

## Styling
* Anyone picking this issue up needs to come up with the styling of focus indication for the above components and get a confirmation from the team before submitting a PR.

## Related
* https://github.com/centerofci/mathesar/issues/2248
* https://github.com/centerofci/mathesar/issues/2215

  The related issues are too high level and cover the entire application which is hard to track, and they are restricted to maintainers who are working on higher priority issues. They also do not provide enough information for an external contributor to pick. This issue is limited in scope inorder to allow external contributors to pick this up.

**Comment by rafiya2003** [comment]
I am interested. Can you please assign me.

**Comment by Rohxn16** [comment]
I have worked with UI and wanna work on this issue.

**Comment by dikwickley** [comment]
hey @pavish i would like to work on this. Please assign this to me.

**Comment by pavish** [comment]
@dikwickley Sure, go ahead.

**Comment by dikwickley** [comment]
@pavish I have added the following focus style to pretty much all the elements mentioned

```
outline: 2px solid var(--slate-300);
outline-offset: 1px;
```

Button:
To the global button class so any element of using `btn` class will have this
<img width="346" alt="image" src="https://github.com/centerofci/mathesar/assets/31622972/8d47a24b-eb10-43d3-9302-e25f8eaf7169">

Schema Row:
It already had a focus effect, but it was not very visible so updated it a bit
before:
<img width="816" alt="image" src="https://github.com/centerofci/mathesar/assets/31622972/272a1b1c-0bdc-4ff2-a96b-f6bd4d855310">
after:
<img width="816" alt="image" src="https://github.com/centerofci/mathesar/assets/31622972/d80bd322-f228-468a-947f-007067877eed">


As for the Table Card, here is how it looks now:

https://github.com/centerofci/mathesar/assets/31622972/162d2abc-126b-4998-8dd1-11aa7e695782

I have chosen a very subtle focus indication. Can you please take a look (or pass it to the design team) for confirmation? Let me know if anything needs to be updated.
I'll work on App Header and Breadcrubs in the meantime.

**Comment by seancolsen** [comment]
@pavish I've assigned you to this to provide feedback. Please unassign yourself when done.

**Comment by pavish** [comment]
@dikwickley 

## Schema Row
- Looks good to me
- Make sure that the right button (actions menu with three dots) is visually appealing when focused.

## Table Card

I'd like the following changes:
- The outline should follow the border radius that is visible to the user.
- Make the right button (actions menu with three dots) more visually appealing when focused.

## Button

> To the global button class so any element of using `btn` class will have this

I think it's okay to add the styles you've mentioned to the global button class. However, there are different button appearances around the app, and a common outline color would affect some of them. This is a technical debt which needs to be cleaned up a bit.

For eg., The breadcrumb selector has a arrow icon in a button, and top navigation pane has a number of buttons that use a 'ghost' appearance. This kind of button has a transparent background color and border. The fixed outline color you've used will affect them, making them less visually appealing.

![Screenshot 2023-11-17 at 3 13 53 PM](https://github.com/centerofci/mathesar/assets/11850603/ea0bd723-d1bd-4da1-93ee-c6348d3726d6)

#### What I'd expect:
- Outline color should depend on the type of the button.
- Check places where 'ghost' button is used, and check if they are visually appealing with the focus indications. Eg., In the above screenshot, the 'Settings' button on the far right is larger than the 'Shortcuts' button. So far we've used the ghost appearance, and it's not been visible to the user. Now, with focus indications, it's important we make them the same size to make it visually appealing. Also, experiment with different outline colors for places like these.

#### Extra - Doesn't have to be part of the work in this issue
If you had the time and would like to clean up the styles, I'd recommend the following:
- Deprecate the 'ghost' appearance. We don't have to remove it right away, but add a comment saying it's deprecated.
- Add a 'custom' appearance option, which does not set any colors in the scss file.
- We should be able to accept cssVariables that contains values for color, background, border-color, and outline-color etc.,
- The styles will look like this:
  ```scss
  .btn {
    ...,
    border-radius: var(--Button__border-radius, var(--Button__internal__border-radius));
    background: var(--Button__background, var(--Button__internal__background));
    border-color: var(--Button__border-color, var(--Button__internal__border-color));
    color: var(--Button__color, var(--Button__internal__color));
    outline-color: var(--Button__outline-color, var(--Button__internal__outline-color));
    
    &:not(:disabled) {
      &:focus {
        border-color: var(--Button__focused__border-color, var(--Button__internal__focused__border-color));
        outline-color: var(--Button__focused__outline-color, var(--Button__internal__focused__outline-color));
      }
    }
    ...,

    &.btn-primary {
      ...,
      --Button__internal__background: var(--brand-500);
      --Button__internal__border-color: var(--brand-500);
      --Button__internal__color: var(--white);
      --Button__internal__focused__outline-color: var(--slate-300);
      --Button__internal__border-radius: var(--size-super-ultra-small);
      ...,
    }
    ...,
  }
  ```
  Note that this is an example and not meant to be followed as-is.
- Both the following component calls should work:
  ```svelte
  <Button appearance="custom" cssVariables={{
    --Button__background: var(--brand-500);
    --Button__border-color: var(--brand-500);
  }}>
  ```svelte
  or like this:
  ```
  <div style="--Button__background: blue;">
    <Button appearance="plain"/>
  </div>
  ```
- Refer components like 'Menu' to check how to add the `cssVariables` prop. Do not use Svelte's default method to pass css variables as `--style-props`, as it automatically adds new elements to the DOM which we have no control over.
- The variables provided during component call should take priority over internally used variables.
- Feel free to experiment with this. Let me know if you have questions.
