### ISSUE TITLE
Add Docker secrets support to Docker Compose configuration

### ISSUE THREAD

**Issue by dralshehri** [mathesar-foundation/mathesar#4596]
## Problem
Mathesar's current Docker Compose configuration requires sensitive data like `SECRET_KEY` and `POSTGRES_PASSWORD` to be passed as environment variables. The `SECRET_KEY` currently requires manual setup with `${SECRET_KEY:?}` and `POSTGRES_PASSWORD` defaults to `mathesar`. This creates security risks as these credentials are visible in process lists, logs, and environment variable dumps, especially problematic in production environments.

## Proposed solution
Add support for Docker secrets in Mathesar's Docker Compose configuration by:

1. **Adding secrets section** to the compose file:
```yaml
secrets:
  secret_key:
    external: true
  postgres_password:
    external: true
```

2. **Mounting secrets** to relevant services:
```yaml
services:
  service:
    secrets:
      - secret_key
      - postgres_password
  db:
    secrets:
      - postgres_password
```

3. **Updating Mathesar** to read from secret files (e.g., `/run/secrets/secret_key`, `/run/secrets/postgres_password`) as an alternative to environment variables, maintaining backward compatibility with the current `x-config` approach.

## Additional context
This would allow users to securely manage credentials using:
```bash
docker secret create secret_key /path/to/secret_key.txt
docker secret create postgres_password /path/to/postgres_password.txt
```

Benefits include encrypted secrets at rest/transit, avoiding exposure in environment variables, and meeting enterprise security requirements. The current `x-config` anchor system could be extended to support both environment variables and Docker secrets.

**Reference:** https://docs.docker.com/compose/how-tos/use-secrets/
